const mongoose = require("mongoose");

const TenderSchema = new mongoose.Schema({
    id: Number,
    documentType: {
        type: String,
        default: "GeM ATC Document",
    },
    userId: { type: Number, default: null },
    createdBy: {
        id: Number,
        fullName: String,
        email: String,
        departmentName: String,
        designation: String,
    },
    departmentName: String,
    departmentEmail: String,
    tenderInvitingAuthority: String,
    tenderCategory: String,
    tenderType: String,
    tenderName: String,
    tenderNo: String,
    estimatedCost: Number,
    estimatedCostWords: String,
    itemQuantity: String,
    procurementLocations: String,
    itemsList: [
        {
            srNo: Number,
            name: String,
            specs: String,
            quantity: String,
        }
    ],
    bidValidity: Number,
    emdRequired: String,
    emdAmount: Number,
    emdAmountWords: String,
    pbgRequired: String,
    pbgAmount: Number,
    pbgAmountWords: String,
    emdPledgeOfficer: String,
    bidStartDate: Date,
    bidEndDate: Date,
    bidEndTime: String,
    publishDate: Date,
    offlineSubmissionDate: Date,
    techEvalDate: Date,
    techEvalTime: String,
    openingVenue: String,
    isPreBidRequired: String,
    preBidDate: Date,
    deliveryDays: Number,
    warrantyDurable: String,
    warrantyConsumable: String,
    courtJurisdiction: String,
    selectedTermIds: [Number],
    isAnnexureRequired: { type: Boolean, default: true },
    selectedAnnexureIds: { type: [Number], default: [] },
    annexureCustomData: { type: Object, default: {} },
    variables: Object,
    createdAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model("Tender", TenderSchema);
